import { test, expect } from "./authenticated";

test("files stay in chat through upload, exact statistics, Excel delivery and reload", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "有什么想交给妮米？" })).toBeVisible();
  await page.getByRole("button", { name: "新对话", exact: true }).click();
  await page.getByLabel("上传对话附件").setInputFiles({ name: "生活账单.csv", mimeType: "text/csv", buffer: Buffer.from("类型,金额\n餐饮,0.1\n餐饮,0.2\n交通,10\n") });
  await expect(page.locator(".composer-attachments").getByRole("button", { name: "预览 生活账单.csv" })).toBeVisible();
  await page.locator(".composer-attachments").getByRole("button", { name: "预览 生活账单.csv" }).click();
  const source = page.getByRole("dialog", { name: "生活账单.csv资料预览" });
  await expect(source.getByText("0.2", { exact: true })).toBeVisible();
  await source.getByRole("button", { name: "关闭资料预览" }).click();
  await page.getByLabel("告诉妮米你想做的事").fill("统计这份账单并生成Excel汇总");
  await page.getByRole("button", { name: "发送消息", exact: true }).click();
  const history = page.getByLabel("对话内容", { exact: true });
  await expect(history.locator(".assistant .chat-reply").last()).toContainText("已统计完整账单并生成 Excel 汇总");
  await expect(page.locator(".composer-attachments")).toHaveCount(0);
  await history.getByRole("button", { name: "预览 生活账单汇总.xlsx" }).click();
  const result = page.getByRole("dialog", { name: "生活账单汇总.xlsx资料预览" });
  await expect(result.getByText("10.30000000", { exact: true })).toBeVisible();
  const downloadEvent = page.waitForEvent("download");
  await result.getByRole("link", { name: "下载文件", exact: true }).click();
  const download = await downloadEvent;
  expect(download.suggestedFilename()).toBe("生活账单汇总.xlsx");
  const stream = await download.createReadStream(); const chunks: Buffer[] = [];
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk));
  expect(Buffer.concat(chunks).subarray(0, 2).toString()).toBe("PK");
  await result.getByRole("button", { name: "关闭资料预览" }).click();
  await page.reload();
  await expect(history.getByRole("button", { name: "预览 生活账单汇总.xlsx" })).toBeVisible();
  const list = await (await page.request.get("/api/v1/conversations")).json();
  const detail = await (await page.request.get(`/api/v1/conversations/${list.conversations[0].id}`)).json();
  expect(detail.turns[0].files.map((f: { kind: string }) => f.kind)).toEqual(["upload", "artifact"]);
  expect(detail.turns[0].steps.filter((s: { kind: string }) => s.kind === "TOOL").map((s: { name: string }) => s.name)).toEqual(["list_files", "analyze_table", "create_artifact"]);
  await page.screenshot({ path: "test-results/nemi-v08-files.png", fullPage: true, animations: "disabled" });
  await page.setViewportSize({ width: 390, height: 844 });
  await history.getByRole("button", { name: "预览 生活账单汇总.xlsx" }).click();
  await expect(result.getByText("10.30000000", { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/nemi-v08-file-preview-mobile.png", fullPage: true, animations: "disabled" });
});
